### ISSUE TITLE
async_pipe does not meet AsyncReadStream requirements

### ISSUE THREAD

**Issue by gulachek** [boostorg/process#196]
The async_pipe class does not meet the requirements for an [AsyncReadStream](https://www.boost.org/doc/libs/1_75_0/doc/html/boost_asio/reference/AsyncReadStream.html).  The get_executor() member should be implemented, probably to just return the executor of the underlying implementation.  The impact is that async operations following the guidelines of posting work on the associated executor of the operation will not compile since this member is not available.

**Comment by olk** [comment]
I pushed pull request #197 in order to fix this issue.

**Comment by gulachek** [comment]
I don't understand how using post() instead of dispatch() fulfills the request to add a get_executor() member function. 197 doesn't fix this.
